[package]
name = "rackc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"]}
nom = "7.1.2"
nom_locate = "4.0.0"
